services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "mssql"
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - "1433:1433"
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
  user.api:
    image: user.api
    depends_on:
      - sqldata
      - rabbitmq
    build:
      context: .
      dockerfile: src/User/User.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - EventBusConnection=rabbitmq
    ports:
      - "80"
      - "5001:443"
  notification.api:
    image: notification.api
    depends_on:
      - rabbitmq
      - sqldata
    build:
      context: .
      dockerfile: src/Notification/Notification.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - EventBusConnection=rabbitmq
    ports:
      - "80"
      - "5002:443"
